try
    // {
    //     if(b==0){
    //         throw 1;
    //     }
    // }
    // catch(int c)
    // {
    //     cout<<"Here is a runtime error..";
    //     exit(0);
    // }